version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: budget-tracker
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/budget-tracker
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: [backend]
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:4000


volumes:
  mongo-data:
