version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      MONGO_INITDB_DATABASE: budget-tracker
    volumes:
      - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_SERVER: mongo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://admin:qwerty@mongo:27017/budget-tracker?authSource=admin
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    depends_on: [backend]
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents overwriting node_modules


volumes:
  mongo-data:
